# Generated by Django 5.0.3 on 2024-03-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextras',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
    ]
