# Generated by Django 5.0.3 on 2024-03-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
    ]
