# Generated by Django 5.0.3 on 2024-03-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.FileField(default='Null', upload_to=''),
            preserve_default=False,
        ),
    ]
